export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';

export const ETSY_LOAD_ITEMS = 'ETSY_LOAD_ITEMS';
export const ETSY_CATEGORY_STEP = 'ETSY_CATEGORY_STEP';
export const GALLERY_ITEM_CLICK = 'GALLERY_ITEM_CLICK';

export const IG_NONFOLLOWERS = 'IG_NONFOLLOWERS';
export const IG_UNFOLLOW = 'IG_UNFOLLOW';

