
export const ETSY_CATEGORY_STEP = 'ETSY_CATEGORY_STEP';
export const GALLERY_ITEM_CLICK = 'GALLERY_ITEM_CLICK';

export const IG_NONFOLLOWERS = 'IG_NONFOLLOWERS';
export const IG_UNFOLLOW = 'IG_UNFOLLOW';

export const ADD_TO_CART = 'ADD_TO_CART';
export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST';
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS';
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE';
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';
